/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_TextCMake */

#ifndef _Included_com_example_jni_TextCMake
#define _Included_com_example_jni_TextCMake
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_TextCMake
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jni_TextCMake_getJniString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
