/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_CTransferJava */

#ifndef _Included_com_example_jni_CTransferJava
#define _Included_com_example_jni_CTransferJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_CTransferJava
 * Method:    transferJavaFun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jni_CTransferJava_transferJavaFun
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jni_CTransferJava
 * Method:    transferJavaFunReturnInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_jni_CTransferJava_transferJavaFunReturnInt
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jni_CTransferJava
 * Method:    transferJavaFunReturnObject
 * Signature: ()Lcom/example/jni/CTransferTextClass;
 */
JNIEXPORT jobject JNICALL Java_com_example_jni_CTransferJava_transferJavaFunReturnObject
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jni_CTransferJava
 * Method:    transferJavaFunOutside
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jni_CTransferJava_transferJavaFunOutside
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jni_CTransferJava
 * Method:    transferJavaFunOutside_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jni_CTransferJava_transferJavaFunOutside_11
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jni_CTransferJava
 * Method:    transferJavaStatic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jni_CTransferJava_transferJavaStatic
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jni_CTransferJava
 * Method:    staticTransferJavaFun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jni_CTransferJava_staticTransferJavaFun
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
